In [1]:
# ===================================================================
# PASO 1: CONFIGURACI√ìN E INSTALACI√ìN DE LIBRER√çAS
# ===================================================================

import pandas as pd
import requests
import sqlite3

print("‚úÖ Librer√≠as importadas.")

‚úÖ Librer√≠as importadas.

In [2]:
pd.set_option('display.max_columns', None) ## muestra todos los datos

In [3]:
# ===================================================================
# PASO 2: EXTRACCI√ìN (EXTRACT) DE LOS DATOS
# ===================================================================

# La plataforma datos.gov.co usa la API de Socrata. Podemos usarla para
# descargar los datos directamente, lo que es m√°s eficiente que bajar un CSV.
# Aumentamos el l√≠mite para traer m√°s filas (ajusta si es necesario).
api_url = "https://www.datos.gov.co/resource/nudc-7mev.json?$limit=50000"

print(f"üì• Extrayendo datos desde: {api_url}")

try:
    response = requests.get(api_url)
    response.raise_for_status()  # Lanza un error si la petici√≥n falla (ej: 404)
    data = response.json()
    df_raw = pd.DataFrame(data)
    print(f"‚úÖ ¬°Extracci√≥n exitosa! Se cargaron {len(df_raw)} filas.")
    display(df_raw.head())

except requests.exceptions.RequestException as e:
    print(f"‚ùå Error al extraer los datos: {e}")
    df_raw = pd.DataFrame() # Creamos un dataframe vac√≠o para evitar errores posteriores

except Exception as e:
    print(f"‚ùå Ocurri√≥ un error inesperado: {e}")
    df_raw = pd.DataFrame()

üì• Extrayendo datos desde: https://www.datos.gov.co/resource/nudc-7mev.json?$limit=50000
‚úÖ ¬°Extracci√≥n exitosa! Se cargaron 14585 filas.

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,cobertura_neta_transici_n,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,cobertura_bruta,cobertura_bruta_transici_n,cobertura_bruta_primaria,cobertura_bruta_secundaria,cobertura_bruta_media,deserci_n,deserci_n_transici_n,deserci_n_primaria,deserci_n_secundaria,deserci_n_media,aprobaci_n,aprobaci_n_transici_n,aprobaci_n_primaria,aprobaci_n_secundaria,aprobaci_n_media,reprobaci_n,reprobaci_n_transici_n,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
0,2023,05004,Abriaqu√≠,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,44.19,63.33,51.53,40.23,66.8,58.14,72.86,66.87,56.32,1.19,0,1.31,0,4.08,92.26,0,96.73,83.49,93.88,6.55,0,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN
1,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,33.91,48.89,44.9,21.3,62.98,54.2,65.19,69.6,48.54,5.56,6.95,4.99,6.11,5.26,87.67,0,87.9,84.5,92.98,6.78,0,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN
2,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,17.58,25.33,26.43,10.75,38.58,36.36,37.28,46.1,26.16,7.85,15,8.43,6.36,4.69,82.68,3.33,84.64,79.51,87.5,9.47,3.33,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN
3,2023,97001,Mit√∫,97,Vaup√©s,3831,Vaup√©s (ETC),10986,59.57,59.57,42.76,55.95,43.51,17.06,70.65,64.9,76.96,72.92,53.12,3.95,2.27,1.84,6.77,5.47,90.71,0.57,94.12,84.91,89.93,5.34,0.57,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN
4,2023,97161,Caruru,97,Vaup√©s,3831,Vaup√©s (ETC),1228,51.3,51.3,76.32,52.29,33.71,11.94,55.54,92.11,65.21,51.12,27.36,8.36,4.29,3.05,15.72,14.55,82.4,0,89.63,69,78.18,9.24,0,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN

In [4]:
df_raw

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,cobertura_neta_transici_n,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,cobertura_bruta,cobertura_bruta_transici_n,cobertura_bruta_primaria,cobertura_bruta_secundaria,cobertura_bruta_media,deserci_n,deserci_n_transici_n,deserci_n_primaria,deserci_n_secundaria,deserci_n_media,aprobaci_n,aprobaci_n_transici_n,aprobaci_n_primaria,aprobaci_n_secundaria,aprobaci_n_media,reprobaci_n,reprobaci_n_transici_n,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
0,2023,05004,Abriaqu√≠,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,44.19,63.33,51.53,40.23,66.8,58.14,72.86,66.87,56.32,1.19,0,1.31,0,4.08,92.26,0,96.73,83.49,93.88,6.55,0,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN
1,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,33.91,48.89,44.9,21.3,62.98,54.2,65.19,69.6,48.54,5.56,6.95,4.99,6.11,5.26,87.67,0,87.9,84.5,92.98,6.78,0,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN
2,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,17.58,25.33,26.43,10.75,38.58,36.36,37.28,46.1,26.16,7.85,15,8.43,6.36,4.69,82.68,3.33,84.64,79.51,87.5,9.47,3.33,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN
3,2023,97001,Mit√∫,97,Vaup√©s,3831,Vaup√©s (ETC),10986,59.57,59.57,42.76,55.95,43.51,17.06,70.65,64.9,76.96,72.92,53.12,3.95,2.27,1.84,6.77,5.47,90.71,0.57,94.12,84.91,89.93,5.34,0.57,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN
4,2023,97161,Caruru,97,Vaup√©s,3831,Vaup√©s (ETC),1228,51.3,51.3,76.32,52.29,33.71,11.94,55.54,92.11,65.21,51.12,27.36,8.36,4.29,3.05,15.72,14.55,82.4,0,89.63,69,78.18,9.24,0,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14580,2011,5036,Angel√≥polis,5,Antioquia,3758,Antioquia (ETC),1707,78.85,78.9,56.2,82.4,59.9,26.4,82.8,77.4,105,80.4,40.1,8.14,6.6,6.1,13.17,2.44,86.27,0,90.29,77.32,90.24,5.59,0,3.61,9.5,7.32,0.71,0,0.7,1.08,0,19.57,100
14581,2011,5034,Andes,5,Antioquia,3758,Antioquia (ETC),10244,84.45,84.5,65.1,83.7,62,32.2,91.7,81.1,107.5,89.9,61.4,3.96,3.06,4.3,4.36,1.68,95.46,0,95.12,95.61,95.63,0.58,0,0.58,0.04,2.69,5.41,0.73,5.53,6.9,4.11,24.43,93.44
14582,2011,5031,Amalfi,5,Antioquia,3758,Antioquia (ETC),5552,97.71,97.7,61.7,107.2,65.1,27.3,108.4,77.9,146.8,97.3,53.9,8.75,5.83,8.59,9.49,9.74,91.25,0,91.41,90.51,90.26,0,0,0,0,0,NaN,0.83,NaN,9.93,4.47,20.01,53.45
14583,2011,5030,Amag√°,5,Antioquia,3758,Antioquia (ETC),6631,78.65,78.7,55.3,76.3,70.7,38.9,87.7,74.3,89.8,96.3,73.2,4.16,2.39,3.23,6.12,3.21,86.86,0.24,90.04,79.42,89.34,8.99,0.24,6.73,14.46,7.45,0.42,0,0.24,0.91,0,25.05,83.33
14584,2011,5021,Alejandr√≠a,5,Antioquia,3758,Antioquia (ETC),702,118.52,118.5,82.7,127.6,90.2,48.5,134.9,86.5,159.8,140.8,94,4.03,NaN,NaN,8.46,8.04,92.39,0,97.84,87.15,83.93,3.58,0,2.16,4.39,8.04,0.6,0,0.96,0,0,32.14,81.25

In [5]:
conn = sqlite3.connect('../Datos/Educacion.bd')

In [6]:
df_raw.to_sql('Educacion',conn)

ValueError: Table 'Educacion' already exists.

In [7]:
cursor = conn.cursor()

In [8]:
pd.read_sql('SELECT * FROM Educacion', con=conn)

,index,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,cobertura_neta_transici_n,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,cobertura_bruta,cobertura_bruta_transici_n,cobertura_bruta_primaria,cobertura_bruta_secundaria,cobertura_bruta_media,deserci_n,deserci_n_transici_n,deserci_n_primaria,deserci_n_secundaria,deserci_n_media,aprobaci_n,aprobaci_n_transici_n,aprobaci_n_primaria,aprobaci_n_secundaria,aprobaci_n_media,reprobaci_n,reprobaci_n_transici_n,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
0,0,2023,05004,Abriaqu√≠,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,44.19,63.33,51.53,40.23,66.8,58.14,72.86,66.87,56.32,1.19,0,1.31,0,4.08,92.26,0,96.73,83.49,93.88,6.55,0,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,None,None
1,1,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,33.91,48.89,44.9,21.3,62.98,54.2,65.19,69.6,48.54,5.56,6.95,4.99,6.11,5.26,87.67,0,87.9,84.5,92.98,6.78,0,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,None,None
2,2,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,17.58,25.33,26.43,10.75,38.58,36.36,37.28,46.1,26.16,7.85,15,8.43,6.36,4.69,82.68,3.33,84.64,79.51,87.5,9.47,3.33,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,None,None
3,3,2023,97001,Mit√∫,97,Vaup√©s,3831,Vaup√©s (ETC),10986,59.57,59.57,42.76,55.95,43.51,17.06,70.65,64.9,76.96,72.92,53.12,3.95,2.27,1.84,6.77,5.47,90.71,0.57,94.12,84.91,89.93,5.34,0.57,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,None,None
4,4,2023,97161,Caruru,97,Vaup√©s,3831,Vaup√©s (ETC),1228,51.3,51.3,76.32,52.29,33.71,11.94,55.54,92.11,65.21,51.12,27.36,8.36,4.29,3.05,15.72,14.55,82.4,0,89.63,69,78.18,9.24,0,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14580,14580,2011,5036,Angel√≥polis,5,Antioquia,3758,Antioquia (ETC),1707,78.85,78.9,56.2,82.4,59.9,26.4,82.8,77.4,105,80.4,40.1,8.14,6.6,6.1,13.17,2.44,86.27,0,90.29,77.32,90.24,5.59,0,3.61,9.5,7.32,0.71,0,0.7,1.08,0,19.57,100
14581,14581,2011,5034,Andes,5,Antioquia,3758,Antioquia (ETC),10244,84.45,84.5,65.1,83.7,62,32.2,91.7,81.1,107.5,89.9,61.4,3.96,3.06,4.3,4.36,1.68,95.46,0,95.12,95.61,95.63,0.58,0,0.58,0.04,2.69,5.41,0.73,5.53,6.9,4.11,24.43,93.44
14582,14582,2011,5031,Amalfi,5,Antioquia,3758,Antioquia (ETC),5552,97.71,97.7,61.7,107.2,65.1,27.3,108.4,77.9,146.8,97.3,53.9,8.75,5.83,8.59,9.49,9.74,91.25,0,91.41,90.51,90.26,0,0,0,0,0,None,0.83,None,9.93,4.47,20.01,53.45
14583,14583,2011,5030,Amag√°,5,Antioquia,3758,Antioquia (ETC),6631,78.65,78.7,55.3,76.3,70.7,38.9,87.7,74.3,89.8,96.3,73.2,4.16,2.39,3.23,6.12,3.21,86.86,0.24,90.04,79.42,89.34,8.99,0.24,6.73,14.46,7.45,0.42,0,0.24,0.91,0,25.05,83.33
14584,14584,2011,5021,Alejandr√≠a,5,Antioquia,3758,Antioquia (ETC),702,118.52,118.5,82.7,127.6,90.2,48.5,134.9,86.5,159.8,140.8,94,4.03,None,None,8.46,8.04,92.39,0,97.84,87.15,83.93,3.58,0,2.16,4.39,8.04,0.6,0,0.96,0,0,32.14,81.25

In [9]:
def ejecutar_sql(query, conexion=conn):
    """
    Ejecuta una consulta SQL. Si es un SELECT, muestra el resultado como tabla.
    Si no, ejecuta sin retorno (DROP, CREATE, etc.).
    """
    if query.strip().lower().startswith("select"):
        df = pd.read_sql_query(query, conexion)
        display(df)
    else:
        cursor = conexion.cursor()
        cursor.execute(query)
        conexion.commit()
        print("‚úÖ Consulta ejecutada correctamente.")

In [10]:
ejecutar_sql("DROP TABLE IF EXISTS Educacion_Limpia")

‚úÖ Consulta ejecutada correctamente.

In [11]:
ejecutar_sql("""
CREATE TABLE Educacion_Limpia AS
SELECT
    CAST(a_o AS INTEGER) AS anio,
    
    -- Normalizamos el c√≥digo departamento (ej: '1' ‚Üí '01')
    CASE 
        WHEN LENGTH(TRIM(c_digo_departamento)) = 1 THEN '0' || TRIM(c_digo_departamento)
        ELSE TRIM(c_digo_departamento)
    END AS codigo_departamento,
    
    -- Normalizamos el c√≥digo municipio (ej: '5400' ‚Üí '05400')
    CASE 
        WHEN LENGTH(TRIM(c_digo_municipio)) = 4 THEN '0' || TRIM(c_digo_municipio)
        ELSE TRIM(c_digo_municipio)
    END AS codigo_municipio,
    
    -- Para trazabilidad dejamos nombres tambi√©n
    TRIM(departamento) AS nombre_departamento,
    TRIM(municipio) AS nombre_municipio,
    
    -- Conversi√≥n de m√©tricas
    CAST(poblaci_n_5_16 AS REAL) AS poblacion,
    CAST(tasa_matriculaci_n_5_16 AS REAL) AS tasa_matriculacion,
    CAST(cobertura_neta AS REAL) AS cobertura_neta,
    CAST(aprobaci_n AS REAL) AS aprobacion,
    CAST(reprobaci_n AS REAL) AS reprobacion
    
FROM Educacion
WHERE 
    a_o IS NOT NULL
    AND TRIM(departamento) != 'Nacional'
    AND c_digo_departamento IS NOT NULL
    AND c_digo_municipio IS NOT NULL
    AND poblaci_n_5_16 IS NOT NULL
    AND tasa_matriculaci_n_5_16 IS NOT NULL
    AND cobertura_neta IS NOT NULL;
""")

‚úÖ Consulta ejecutada correctamente.

In [12]:
pd.read_sql('SELECT * FROM Educacion_Limpia', con=conn)

,anio,codigo_departamento,codigo_municipio,nombre_departamento,nombre_municipio,poblacion,tasa_matriculacion,cobertura_neta,aprobacion,reprobacion
0,2023,05,05004,Antioquia,Abriaqu√≠,503.0,62.62,62.62,92.26,6.55
1,2023,95,95025,Guaviare,El Retorno,4438.0,53.27,53.27,87.67,6.78
2,2023,95,95200,Guaviare,Miraflores,2014.0,32.52,32.52,82.68,9.47
3,2023,97,97001,Vaup√©s,Mit√∫,10986.0,59.57,59.57,90.71,5.34
4,2023,97,97161,Vaup√©s,Caruru,1228.0,51.30,51.30,82.40,9.24
...,...,...,...,...,...,...,...,...,...,...
14446,2011,05,05036,Antioquia,Angel√≥polis,1707.0,78.85,78.90,86.27,5.59
14447,2011,05,05034,Antioquia,Andes,10244.0,84.45,84.50,95.46,0.58
14448,2011,05,05031,Antioquia,Amalfi,5552.0,97.71,97.70,91.25,0.00
14449,2011,05,05030,Antioquia,Amag√°,6631.0,78.65,78.70,86.86,8.99
14450,2011,05,05021,Antioquia,Alejandr√≠a,702.0,118.52,118.50,92.39,3.58

In [13]:
ejecutar_sql("DROP TABLE IF EXISTS Dim_Tiempo;")

‚úÖ Consulta ejecutada correctamente.

In [14]:
ejecutar_sql("""
CREATE TABLE Dim_Tiempo AS
SELECT 
    anio,
    ROW_NUMBER() OVER (ORDER BY anio) AS id_tiempo
FROM (
    SELECT DISTINCT anio
    FROM Educacion_Limpia
    WHERE anio IS NOT NULL
)
""")

‚úÖ Consulta ejecutada correctamente.

In [15]:
pd.read_sql('SELECT * FROM Dim_Tiempo;', con=conn)

    anio  id_tiempo
0   2011          1
1   2012          2
2   2013          3
3   2014          4
4   2015          5
5   2016          6
6   2017          7
7   2018          8
8   2019          9
9   2020         10
10  2021         11
11  2022         12
12  2023         13

In [16]:
ejecutar_sql("DROP TABLE IF EXISTS Dim_Geografia;")

‚úÖ Consulta ejecutada correctamente.

In [17]:
ejecutar_sql("""
CREATE TABLE Dim_Geografia AS
SELECT 
    codigo_departamento,
    codigo_municipio,
    ROW_NUMBER() OVER (ORDER BY codigo_departamento, codigo_municipio) AS id_geografia
FROM (
    SELECT DISTINCT codigo_departamento, codigo_municipio
    FROM Educacion_Limpia
    WHERE codigo_departamento IS NOT NULL AND codigo_municipio IS NOT NULL
);
""")

‚úÖ Consulta ejecutada correctamente.

In [ ]:
# Cerramos la conexi√≥n
conn.close()
print("Conexi√≥n a la base de datos cerrada.")

Conexi√≥n a la base de datos cerrada.

: